/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Patient;

import java.awt.Font;
import java.math.BigInteger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.plaf.FontUIResource;


public class FormChangePin extends javax.swing.JFrame {
    ImageIcon icon = new ImageIcon("src/img/connect_failed.png");
    ImageIcon icon1 = new ImageIcon("src/img/icon_success.png");
    /**
     * Creates new form FormChangePin
     */
    String pin, newpin, repin;
    SmartCardWord handler = new SmartCardWord();

    public FormChangePin() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel2 = new javax.swing.JLabel();
        UpdateNewPin = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Right = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        oldPin = new javax.swing.JPasswordField();
        newPin = new javax.swing.JPasswordField();
        reNewPin = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(238, 238, 238));

        kGradientPanel1.setBackground(new java.awt.Color(224, 227, 233));
        kGradientPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(53, 66, 89), 3));
        kGradientPanel1.setkEndColor(new java.awt.Color(224, 227, 233));
        kGradientPanel1.setkStartColor(new java.awt.Color(224, 227, 233));
        kGradientPanel1.setPreferredSize(new java.awt.Dimension(1400, 800));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("ĐỔI MÃ PIN");
        kGradientPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(539, 89, 235, -1));

        UpdateNewPin.setBackground(new java.awt.Color(0, 102, 102));
        UpdateNewPin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        UpdateNewPin.setForeground(new java.awt.Color(255, 255, 255));
        UpdateNewPin.setText("CẬP NHẬT");
        UpdateNewPin.setBorderPainted(false);
        UpdateNewPin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateNewPinActionPerformed(evt);
            }
        });
        kGradientPanel1.add(UpdateNewPin, new org.netbeans.lib.awtextra.AbsoluteConstraints(462, 461, 114, 38));

        back.setBackground(new java.awt.Color(51, 51, 51));
        back.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setText("HỦY");
        back.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        kGradientPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 460, 108, 38));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(53, 66, 89));
        jLabel3.setText("Nhập mã PIN cũ");
        kGradientPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(462, 190, 186, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(53, 66, 89));
        jLabel4.setText("Nhập mã PIN mới");
        kGradientPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(462, 277, 208, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(53, 66, 89));
        jLabel5.setText("Nhập lại mã PIN mới");
        kGradientPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(462, 358, 214, -1));
        kGradientPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(643, 868, -1, 31));

        Right.setBackground(new java.awt.Color(0, 102, 102));
        Right.setPreferredSize(new java.awt.Dimension(400, 500));
        Right.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        Right.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 136, -1, -1));

        jLabel6.setFont(new java.awt.Font("Showcard Gothic", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("SMART CARD");
        Right.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/changepin.png"))); // NOI18N
        Right.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, -1, -1));

        kGradientPanel1.add(Right, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 3, 364, 615));
        kGradientPanel1.add(oldPin, new org.netbeans.lib.awtextra.AbsoluteConstraints(462, 219, 346, 40));
        kGradientPanel1.add(newPin, new org.netbeans.lib.awtextra.AbsoluteConstraints(462, 312, 346, 40));
        kGradientPanel1.add(reNewPin, new org.netbeans.lib.awtextra.AbsoluteConstraints(462, 393, 346, 40));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Secure_50px.png"))); // NOI18N
        kGradientPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, -1, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        Patient customer= new Patient();
        customer.setVisible(true);
        customer.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_backActionPerformed

    private void UpdateNewPinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateNewPinActionPerformed

 // Đặt font cho thông báo
        UIManager.put("OptionPane.messageFont", new FontUIResource(new Font("Times New Roman", Font.BOLD, 24)));

        // Kiểm tra nếu các trường rỗng
        if (oldPin.getPassword().length == 0 || newPin.getPassword().length == 0 || reNewPin.getPassword().length == 0) {
            JOptionPane.showMessageDialog(null, "Mời nhập đủ thông tin!", "", JOptionPane.INFORMATION_MESSAGE, icon);
        } else {
            // Chuyển đổi mảng ký tự sang chuỗi
            String oldPinValue = new String(oldPin.getPassword());
            String newPinValue = new String(newPin.getPassword());
            String reNewPinValue = new String(reNewPin.getPassword());

            // Mã hóa PIN sang định dạng hex
            pin = String.format("%x", new BigInteger(1, oldPinValue.getBytes()));
            newpin = String.format("%x", new BigInteger(1, newPinValue.getBytes()));
            repin = String.format("%x", new BigInteger(1, reNewPinValue.getBytes()));

            // Kiểm tra nếu mã PIN mới và mã PIN xác nhận không trùng nhau
            if (!newpin.equals(repin)) {
                JOptionPane.showMessageDialog(null, "Pin nhập lại không trùng!", "", JOptionPane.INFORMATION_MESSAGE, icon);
            } else {
                // Chuẩn bị dữ liệu yêu cầu
                String dataReq = pin + "03" + newpin;

                // Gọi phương thức đổi mã PIN
                boolean res = handler.changePin(handler.hexStringToByteArray(dataReq));

                // Thông báo kết quả
                if (res) {
                    JOptionPane.showMessageDialog(null, "Cập nhật thành công!", "", JOptionPane.INFORMATION_MESSAGE, icon1);
                    FormChangePin.this.setVisible(false); // Đóng form sau khi cập nhật thành công
                }
            }
        }
    }//GEN-LAST:event_UpdateNewPinActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormChangePin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormChangePin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormChangePin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormChangePin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormChangePin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Right;
    private javax.swing.JButton UpdateNewPin;
    private javax.swing.JButton back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JPasswordField newPin;
    private javax.swing.JPasswordField oldPin;
    private javax.swing.JPasswordField reNewPin;
    // End of variables declaration//GEN-END:variables
}
