/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CustomerCard;

import java.awt.Font;
import java.math.BigInteger;
import java.nio.charset.StandardCharsets;
import java.security.KeyFactory;
import java.security.MessageDigest;
import java.security.PublicKey;
import java.security.Signature;
import java.security.spec.X509EncodedKeySpec;
import java.util.Arrays;
import java.util.Base64;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.plaf.FontUIResource;
//import sun.misc.BASE64Decoder;

/**
 *
 * @author Nga
 */
public class FormVerify extends javax.swing.JFrame {

    ImageIcon icon = new ImageIcon("src/img/connect_failed.png");
    /**
     * Creates new form VerifyPin
     */
    SmartCardWord card = new SmartCardWord();
    RandomString str = new RandomString();
    String pin;
    BigInteger modulusPubkey, exponentPubkey;
    String sign;
    byte signData[];

    public FormVerify() {
        initComponents();
        setLocationRelativeTo(null);
        modulusPubkey = card.getModulusPubkey();
        exponentPubkey = card.getExponentPubkey();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bntEnter = new javax.swing.JButton();
        Right2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtPin = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(53, 66, 89), 3));
        jPanel1.setPreferredSize(new java.awt.Dimension(609, 350));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(53, 66, 89));
        jLabel1.setText("XÁC NHẬN MÃ PIN");

        bntEnter.setBackground(new java.awt.Color(53, 66, 89));
        bntEnter.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bntEnter.setForeground(new java.awt.Color(255, 255, 255));
        bntEnter.setText("Xác nhận");
        bntEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntEnterActionPerformed(evt);
            }
        });

        Right2.setBackground(new java.awt.Color(0, 102, 102));
        Right2.setPreferredSize(new java.awt.Dimension(400, 500));

        jLabel12.setFont(new java.awt.Font("Showcard Gothic", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Smart Card");

        jLabel13.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setText("copyright © company name All rights reserved");

        javax.swing.GroupLayout Right2Layout = new javax.swing.GroupLayout(Right2);
        Right2.setLayout(Right2Layout);
        Right2Layout.setHorizontalGroup(
            Right2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Right2Layout.createSequentialGroup()
                .addGap(0, 84, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(40, 40, 40))
            .addGroup(Right2Layout.createSequentialGroup()
                .addGroup(Right2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Right2Layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jLabel11))
                    .addGroup(Right2Layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(jLabel12)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Right2Layout.setVerticalGroup(
            Right2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Right2Layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(jLabel11)
                .addGap(27, 27, 27)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(78, 78, 78))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Right2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(56, 56, 56))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(txtPin, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(bntEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(112, 112, 112))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel1)
                .addGap(76, 76, 76)
                .addComponent(txtPin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(bntEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(122, Short.MAX_VALUE))
            .addComponent(Right2, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 769, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntEnterActionPerformed
 
UIManager.put("OptionPane.messageFont", new FontUIResource(new Font("Times New Roman", Font.BOLD, 24)));
        if (txtPin.getPassword().length == 0) {
            JOptionPane.showMessageDialog(null, "Mời nhập mã PIN!", "", JOptionPane.INFORMATION_MESSAGE, icon);
            return;
        }

       
        try {
            char[] pinChars = txtPin.getPassword();
        String pin = new String(pinChars);
    // Băm mã PIN bằng SHA-256
    MessageDigest sha256 = MessageDigest.getInstance("SHA-256");
    byte[] pinHash = sha256.digest(pin.getBytes(StandardCharsets.UTF_8));
        
            // Login
            String loginResponse = card.login(pinHash);
            switch (loginResponse) {
                case "1":
                    // PIN correct, perform verification
                    String randomString = str.getAlphaNumericString(10);
                    String randomHex = String.format("%x", new BigInteger(1, randomString.getBytes(StandardCharsets.UTF_8)));
                     byte[] pinBytes = pin.getBytes(StandardCharsets.UTF_8);
                    String pinHex = String.format("%x", new BigInteger(1, pinBytes));
                    String dataToSign = pinHex + "03" + randomHex;
                    signData = card.hexStringToByteArray(dataToSign);
                    String signature = card.getSign(signData);
                    String id = card.getId();

                    if (Verify_Digital_Signature(signData, card.hexStringToByteArray(signature), id)) {
                        JOptionPane.showMessageDialog(null, "Xác thực thành công!", "", JOptionPane.INFORMATION_MESSAGE);
                        NapTien napTien = new NapTien();
                        napTien.setVisible(true);
                        this.dispose();
                    } else {
                        JOptionPane.showMessageDialog(null, "Xác thực thất bại!", "", JOptionPane.ERROR_MESSAGE);
                    }
                    break;
                case "2":
                    JOptionPane.showMessageDialog(null, "Thẻ đã bị khóa!", "", JOptionPane.INFORMATION_MESSAGE);
                    break;
                default:
                    JOptionPane.showMessageDialog(null, "Mã PIN không hợp lệ!", "", JOptionPane.INFORMATION_MESSAGE);
                    break;
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Đã xảy ra lỗi trong quá trình xác thực!", "", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(FormVerify.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bntEnterActionPerformed
 


    public boolean Verify_Digital_Signature(byte[] input, byte[] signatureToVerify, String id) throws Exception {
    // Lấy khóa công khai từ cơ sở dữ liệu
    System.out.println("check id"+ id);
    String publicKeyStr = DBConnection.getPublicKey(id);
    if (publicKeyStr == null || publicKeyStr.isEmpty()) {
        System.err.println("Khoa cong khai khong ton tai trong co so du lieu  ID: " + id);
        return false;
    }

    System.out.println("Public Key String: " + publicKeyStr);

    // Giải mã Base64 thành byte array
    byte[] pubKeyBytes = Base64.getDecoder().decode(publicKeyStr);
    System.out.println("Public Key Bytes: " + Arrays.toString(pubKeyBytes));

    // Tạo đối tượng PublicKey
    KeyFactory keyFactory = KeyFactory.getInstance("RSA");
    PublicKey publicKey = keyFactory.generatePublic(new X509EncodedKeySpec(pubKeyBytes));

    // Khởi tạo Signature cho việc xác thực
    Signature signature = Signature.getInstance("SHA1withRSA");
    signature.initVerify(publicKey);
    signature.update(input);

    // Xác thực chữ ký
    boolean isValid = signature.verify(signatureToVerify);
    System.out.println("Kết quả xác thực: " + isValid);
    return isValid;
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormVerify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormVerify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormVerify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormVerify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormVerify().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Right;
    private javax.swing.JPanel Right1;
    private javax.swing.JPanel Right2;
    private javax.swing.JButton bntEnter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txtPin;
    // End of variables declaration//GEN-END:variables
}

